name:                 dtmc
version:              0.1.0.0
visibility:           public
id:                   dtmc-0.1.0.0-inplace
key:                  dtmc-0.1.0.0-inplace
synopsis:             Type-safe discrete-time Markov chains
abi:                  inplace
exposed:              True
exposed-modules:      Dtmc.Stochastic
import-dirs:
    /Users/a123/CodingProjects/dtmc/dist-newstyle/build/aarch64-osx/ghc-9.10.3/dtmc-0.1.0.0/build

library-dirs:
    /Users/a123/CodingProjects/dtmc/dist-newstyle/build/aarch64-osx/ghc-9.10.3/dtmc-0.1.0.0/build

library-dirs-static:
    /Users/a123/CodingProjects/dtmc/dist-newstyle/build/aarch64-osx/ghc-9.10.3/dtmc-0.1.0.0/build

dynamic-library-dirs:
    /Users/a123/CodingProjects/dtmc/dist-newstyle/build/aarch64-osx/ghc-9.10.3/dtmc-0.1.0.0/build

data-dir:             /Users/a123/CodingProjects/dtmc/.
hs-libraries:         HSdtmc-0.1.0.0-inplace
depends:              base-4.20.2.0-754f hmtrx-0.20.2-ba6d103e
haddock-interfaces:
    /Users/a123/CodingProjects/dtmc/dist-newstyle/build/aarch64-osx/ghc-9.10.3/dtmc-0.1.0.0/doc/html/dtmc/dtmc.haddock

haddock-html:
    /Users/a123/CodingProjects/dtmc/dist-newstyle/build/aarch64-osx/ghc-9.10.3/dtmc-0.1.0.0/doc/html/dtmc
